local Players = game:GetService("Players")
local Player = Players.LocalPlayer
local TweenService = game:GetService("TweenService")
local UserInputService = game:GetService("UserInputService")

local ScreenGui = Instance.new("ScreenGui")
ScreenGui.Name = "InfMoneyGUI"
ScreenGui.Parent = Player:WaitForChild("PlayerGui")
ScreenGui.ResetOnSpawn = false

local MainFrame = Instance.new("Frame")
MainFrame.Size = UDim2.new(0, 200, 0, 60)
MainFrame.Position = UDim2.new(0.5, -100, 0.5, -30)
MainFrame.BackgroundColor3 = Color3.fromRGB(30, 30, 40)
MainFrame.BackgroundTransparency = 0.2
MainFrame.BorderSizePixel = 0
MainFrame.Active = true
MainFrame.Draggable = true
MainFrame.Selectable = true
MainFrame.Parent = ScreenGui

local UICorner = Instance.new("UICorner")
UICorner.CornerRadius = UDim.new(0, 8)
UICorner.Parent = MainFrame

local InfButton = Instance.new("TextButton")
InfButton.Text = "INF MONEY"
InfButton.Size = UDim2.new(0.9, 0, 0.7, 0)
InfButton.Position = UDim2.new(0.05, 0, 0.15, 0)
InfButton.BackgroundColor3 = Color3.fromRGB(255, 50, 50)
InfButton.TextColor3 = Color3.fromRGB(255, 255, 255)
InfButton.Font = Enum.Font.GothamBold
InfButton.TextSize = 16
InfButton.Parent = MainFrame


local ButtonCorner = Instance.new("UICorner")
ButtonCorner.CornerRadius = UDim.new(0, 6)
ButtonCorner.Parent = InfButton


InfButton.MouseButton1Click:Connect(function()

	while true do
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()
game:GetService("ReplicatedStorage")["Remotes"]["ClaimDailyQuest"]:FireServer()

    wait(0.1)

    end
end)

InfButton.MouseEnter:Connect(function()
    TweenService:Create(InfButton, TweenInfo.new(0.1), {
        BackgroundColor3 = Color3.fromRGB(255, 80, 80),
        TextColor3 = Color3.fromRGB(255, 255, 255)
    }):Play()
end)

InfButton.MouseLeave:Connect(function()
    TweenService:Create(InfButton, TweenInfo.new(0.1), {
        BackgroundColor3 = Color3.fromRGB(255, 50, 50),
        TextColor3 = Color3.fromRGB(255, 255, 255)
    }):Play()
end)

local dragging
local dragInput
local dragStart
local startPos

local function update(input)
    local delta = input.Position - dragStart
    MainFrame.Position = UDim2.new(startPos.X.Scale, startPos.X.Offset + delta.X, startPos.Y.Scale, startPos.Y.Offset + delta.Y)
end

MainFrame.InputBegan:Connect(function(input)
    if input.UserInputType == Enum.UserInputType.MouseButton1 then
        dragging = true
        dragStart = input.Position
        startPos = MainFrame.Position
        
        input.Changed:Connect(function()
            if input.UserInputState == Enum.UserInputState.End then
                dragging = false
            end
        end)
    end
end)

MainFrame.InputChanged:Connect(function(input)
    if input.UserInputType == Enum.UserInputType.MouseMovement then
        dragInput = input
    end
end)

UserInputService.InputChanged:Connect(function(input)
    if input == dragInput and dragging then
        update(input)
    end
end)
